/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/api-components/': RouteRecordInfo<'/api-components/', '/api-components', Record<never, never>, Record<never, never>>,
    '/form/': RouteRecordInfo<'/form/', '/form', Record<never, never>, Record<never, never>>,
    '/layout/': RouteRecordInfo<'/layout/', '/layout', Record<never, never>, Record<never, never>>,
    '/menu/': RouteRecordInfo<'/menu/', '/menu', Record<never, never>, Record<never, never>>,
    '/modal/': RouteRecordInfo<'/modal/', '/modal', Record<never, never>, Record<never, never>>,
    '/modal/components/AsyncModal': RouteRecordInfo<'/modal/components/AsyncModal', '/modal/components/AsyncModal', Record<never, never>, Record<never, never>>,
    '/modal/components/ConfirmModal': RouteRecordInfo<'/modal/components/ConfirmModal', '/modal/components/ConfirmModal', Record<never, never>, Record<never, never>>,
    '/modal/components/FormModal': RouteRecordInfo<'/modal/components/FormModal', '/modal/components/FormModal', Record<never, never>, Record<never, never>>,
    '/modal/components/SelectModal': RouteRecordInfo<'/modal/components/SelectModal', '/modal/components/SelectModal', Record<never, never>, Record<never, never>>,
    '/modal/README': RouteRecordInfo<'/modal/README', '/modal/README', Record<never, never>, Record<never, never>>,
    '/README': RouteRecordInfo<'/README', '/README', Record<never, never>, Record<never, never>>,
    '/search/': RouteRecordInfo<'/search/', '/search', Record<never, never>, Record<never, never>>,
    '/search/simple': RouteRecordInfo<'/search/simple', '/search/simple', Record<never, never>, Record<never, never>>,
    '/select/': RouteRecordInfo<'/select/', '/select', Record<never, never>, Record<never, never>>,
    '/select/components/AllFeatures': RouteRecordInfo<'/select/components/AllFeatures', '/select/components/AllFeatures', Record<never, never>, Record<never, never>>,
    '/select/components/ErrorHandling': RouteRecordInfo<'/select/components/ErrorHandling', '/select/components/ErrorHandling', Record<never, never>, Record<never, never>>,
    '/select/components/ManualLoad': RouteRecordInfo<'/select/components/ManualLoad', '/select/components/ManualLoad', Record<never, never>, Record<never, never>>,
    '/select/components/MaxTagExample': RouteRecordInfo<'/select/components/MaxTagExample', '/select/components/MaxTagExample', Record<never, never>, Record<never, never>>,
    '/select/components/TagRenderExample': RouteRecordInfo<'/select/components/TagRenderExample', '/select/components/TagRenderExample', Record<never, never>, Record<never, never>>,
    '/select/CUSTOM_RENDER': RouteRecordInfo<'/select/CUSTOM_RENDER', '/select/CUSTOM_RENDER', Record<never, never>, Record<never, never>>,
    '/select/custom-render': RouteRecordInfo<'/select/custom-render', '/select/custom-render', Record<never, never>, Record<never, never>>,
    '/select/event-example': RouteRecordInfo<'/select/event-example', '/select/event-example', Record<never, never>, Record<never, never>>,
    '/select/EXAMPLES': RouteRecordInfo<'/select/EXAMPLES', '/select/EXAMPLES', Record<never, never>, Record<never, never>>,
    '/select/INDEX': RouteRecordInfo<'/select/INDEX', '/select/INDEX', Record<never, never>, Record<never, never>>,
    '/select/README': RouteRecordInfo<'/select/README', '/select/README', Record<never, never>, Record<never, never>>,
    '/select/simple': RouteRecordInfo<'/select/simple', '/select/simple', Record<never, never>, Record<never, never>>,
    '/table/': RouteRecordInfo<'/table/', '/table', Record<never, never>, Record<never, never>>,
  }
}
