/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/demos/': RouteRecordInfo<'/demos/', '/demos', Record<never, never>, Record<never, never>>,
    '/demos/base-modal/': RouteRecordInfo<'/demos/base-modal/', '/demos/base-modal', Record<never, never>, Record<never, never>>,
    '/demos/base-modal/async': RouteRecordInfo<'/demos/base-modal/async', '/demos/base-modal/async', Record<never, never>, Record<never, never>>,
    '/demos/base-modal/basic': RouteRecordInfo<'/demos/base-modal/basic', '/demos/base-modal/basic', Record<never, never>, Record<never, never>>,
    '/demos/base-modal/form': RouteRecordInfo<'/demos/base-modal/form', '/demos/base-modal/form', Record<never, never>, Record<never, never>>,
    '/demos/base-modal/modals/FormModal': RouteRecordInfo<'/demos/base-modal/modals/FormModal', '/demos/base-modal/modals/FormModal', Record<never, never>, Record<never, never>>,
    '/demos/base-modal/modals/NestedModal': RouteRecordInfo<'/demos/base-modal/modals/NestedModal', '/demos/base-modal/modals/NestedModal', Record<never, never>, Record<never, never>>,
    '/demos/base-modal/modals/SimpleModal': RouteRecordInfo<'/demos/base-modal/modals/SimpleModal', '/demos/base-modal/modals/SimpleModal', Record<never, never>, Record<never, never>>,
    '/demos/base-modal/nested': RouteRecordInfo<'/demos/base-modal/nested', '/demos/base-modal/nested', Record<never, never>, Record<never, never>>,
    '/demos/dropdown-button/basic': RouteRecordInfo<'/demos/dropdown-button/basic', '/demos/dropdown-button/basic', Record<never, never>, Record<never, never>>,
    '/demos/schema-detail/': RouteRecordInfo<'/demos/schema-detail/', '/demos/schema-detail', Record<never, never>, Record<never, never>>,
    '/demos/schema-detail/advanced': RouteRecordInfo<'/demos/schema-detail/advanced', '/demos/schema-detail/advanced', Record<never, never>, Record<never, never>>,
    '/demos/schema-detail/basic': RouteRecordInfo<'/demos/schema-detail/basic', '/demos/schema-detail/basic', Record<never, never>, Record<never, never>>,
    '/demos/schema-detail/columns': RouteRecordInfo<'/demos/schema-detail/columns', '/demos/schema-detail/columns', Record<never, never>, Record<never, never>>,
    '/demos/schema-detail/custom': RouteRecordInfo<'/demos/schema-detail/custom', '/demos/schema-detail/custom', Record<never, never>, Record<never, never>>,
    '/demos/schema-detail/groups': RouteRecordInfo<'/demos/schema-detail/groups', '/demos/schema-detail/groups', Record<never, never>, Record<never, never>>,
    '/demos/schema-detail/README': RouteRecordInfo<'/demos/schema-detail/README', '/demos/schema-detail/README', Record<never, never>, Record<never, never>>,
    '/demos/schema-form/': RouteRecordInfo<'/demos/schema-form/', '/demos/schema-form', Record<never, never>, Record<never, never>>,
    '/demos/schema-form/async': RouteRecordInfo<'/demos/schema-form/async', '/demos/schema-form/async', Record<never, never>, Record<never, never>>,
    '/demos/schema-form/basic': RouteRecordInfo<'/demos/schema-form/basic', '/demos/schema-form/basic', Record<never, never>, Record<never, never>>,
    '/demos/schema-form/custom': RouteRecordInfo<'/demos/schema-form/custom', '/demos/schema-form/custom', Record<never, never>, Record<never, never>>,
    '/demos/schema-form/dynamic': RouteRecordInfo<'/demos/schema-form/dynamic', '/demos/schema-form/dynamic', Record<never, never>, Record<never, never>>,
    '/demos/schema-form/layout': RouteRecordInfo<'/demos/schema-form/layout', '/demos/schema-form/layout', Record<never, never>, Record<never, never>>,
    '/demos/schema-form/validation': RouteRecordInfo<'/demos/schema-form/validation', '/demos/schema-form/validation', Record<never, never>, Record<never, never>>,
    '/demos/schema-page/': RouteRecordInfo<'/demos/schema-page/', '/demos/schema-page', Record<never, never>, Record<never, never>>,
    '/demos/schema-page/basic': RouteRecordInfo<'/demos/schema-page/basic', '/demos/schema-page/basic', Record<never, never>, Record<never, never>>,
    '/demos/schema-page/custom-render': RouteRecordInfo<'/demos/schema-page/custom-render', '/demos/schema-page/custom-render', Record<never, never>, Record<never, never>>,
    '/demos/schema-table/': RouteRecordInfo<'/demos/schema-table/', '/demos/schema-table', Record<never, never>, Record<never, never>>,
    '/demos/schema-table/actions': RouteRecordInfo<'/demos/schema-table/actions', '/demos/schema-table/actions', Record<never, never>, Record<never, never>>,
    '/demos/schema-table/advanced': RouteRecordInfo<'/demos/schema-table/advanced', '/demos/schema-table/advanced', Record<never, never>, Record<never, never>>,
    '/demos/schema-table/api': RouteRecordInfo<'/demos/schema-table/api', '/demos/schema-table/api', Record<never, never>, Record<never, never>>,
    '/demos/schema-table/basic': RouteRecordInfo<'/demos/schema-table/basic', '/demos/schema-table/basic', Record<never, never>, Record<never, never>>,
    '/demos/schema-table/toolbar': RouteRecordInfo<'/demos/schema-table/toolbar', '/demos/schema-table/toolbar', Record<never, never>, Record<never, never>>,
    '/demos/search-form/': RouteRecordInfo<'/demos/search-form/', '/demos/search-form', Record<never, never>, Record<never, never>>,
    '/demos/search-form/advanced': RouteRecordInfo<'/demos/search-form/advanced', '/demos/search-form/advanced', Record<never, never>, Record<never, never>>,
    '/demos/search-form/basic': RouteRecordInfo<'/demos/search-form/basic', '/demos/search-form/basic', Record<never, never>, Record<never, never>>,
    '/demos/search-form/collapse': RouteRecordInfo<'/demos/search-form/collapse', '/demos/search-form/collapse', Record<never, never>, Record<never, never>>,
    '/demos/search-form/layout': RouteRecordInfo<'/demos/search-form/layout', '/demos/search-form/layout', Record<never, never>, Record<never, never>>,
    '/demos/text-ellipsis/': RouteRecordInfo<'/demos/text-ellipsis/', '/demos/text-ellipsis', Record<never, never>, Record<never, never>>,
    '/demos/text-ellipsis/basic': RouteRecordInfo<'/demos/text-ellipsis/basic', '/demos/text-ellipsis/basic', Record<never, never>, Record<never, never>>,
    '/demos/text-ellipsis/methods': RouteRecordInfo<'/demos/text-ellipsis/methods', '/demos/text-ellipsis/methods', Record<never, never>, Record<never, never>>,
    '/demos/text-ellipsis/README': RouteRecordInfo<'/demos/text-ellipsis/README', '/demos/text-ellipsis/README', Record<never, never>, Record<never, never>>,
    '/demos/text-ellipsis/table': RouteRecordInfo<'/demos/text-ellipsis/table', '/demos/text-ellipsis/table', Record<never, never>, Record<never, never>>,
    '/demos/text-ellipsis/tooltip': RouteRecordInfo<'/demos/text-ellipsis/tooltip', '/demos/text-ellipsis/tooltip', Record<never, never>, Record<never, never>>,
    '/README': RouteRecordInfo<'/README', '/README', Record<never, never>, Record<never, never>>,
    '/redirect': RouteRecordInfo<'/redirect', '/redirect', Record<never, never>, Record<never, never>>,
  }
}
